export BUILT_PRODUCTS_DIR="/Users/possen/Library/Developer/Xcode/DerivedData/Fothello-aboynlpftazdsufuiunuyxampsfc/Build/Products/Debug-iphoneos"
export CURRENT_ARCH="arm64"
export OBJECT_FILE_DIR_normal="/Users/possen/Library/Developer/Xcode/DerivedData/Fothello-aboynlpftazdsufuiunuyxampsfc/Build/Intermediates/Fothello.build/Debug-iphoneos/FothelloIOS.build/Objects-normal"
export OBJROOT="/Users/possen/Library/Developer/Xcode/DerivedData/Fothello-aboynlpftazdsufuiunuyxampsfc/Build/Intermediates"
export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR="YES"
export SRCROOT="/Users/possen/Projects/Fothello"
