export BUILT_PRODUCTS_DIR="/Users/possen/Library/Developer/Xcode/DerivedData/Fothello-aboynlpftazdsufuiunuyxampsfc/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/possen/Library/Developer/Xcode/DerivedData/Fothello-aboynlpftazdsufuiunuyxampsfc/Build/Intermediates/CodeCoverage/Intermediates/Fothello.build/Debug-iphonesimulator/FothelloIOS.build/Objects-normal"
export OBJROOT="/Users/possen/Library/Developer/Xcode/DerivedData/Fothello-aboynlpftazdsufuiunuyxampsfc/Build/Intermediates/CodeCoverage/Intermediates"
export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR="YES"
export SRCROOT="/Users/possen/Projects/Fothello"
